# SCRIPT/config.yaml

# Global options that apply to both transcribers.
transcription_options:
    # Language code for transcription (e.g., "en" for English, "el" for Greek).
    # This setting applies to both the main and preview transcribers.
    language: "el"

    # If true, the live preview transcriber will be enabled.
    # If false, only the main transcriber will be used, and no live preview
    # will be shown. This can save GPU resources.
    enable_preview_transcriber: true


# Configuration for the main, high-accuracy transcription.
# This instance processes the entire recording at the end for the best quality.
main_transcriber:
    # Model from HuggingFace to use for transcription.
    # Examples: "Systran/faster-whisper-large-v3", "Systran/faster-whisper-medium"
    model: "Systran/faster-whisper-large-v3"

    # Compute type for the model. "default" is recommended.
    # Options: "default", "auto", "int8", "int8_float16", "int16", "float16", "float32"
    compute_type: "default"

    # Hardware device to run the model on. "cuda" for NVIDIA GPUs, "cpu" for CPU.
    device: "cuda"

    # Index of the GPU to use if you have multiple GPUs. Usually 0.
    gpu_device_index: 0

    # Transcription engine batch size. Higher may be faster on powerful GPUs.
    batch_size: 16

    # Beam size for the Whisper model's decoding. Higher can improve accuracy but is slower.
    beam_size: 5

    # An optional initial prompt to guide the model's transcription style or context.
    # Example: "This is a technical transcript. ZFS, Kubernetes, TCP/IP."
    initial_prompt: null # Use null or leave blank for no prompt.

    # Use faster-whisper's built-in VAD to filter out silence for better accuracy.
    faster_whisper_vad_filter: true

    # Prevent the library from creating its own log file (realtimestt.log).
    no_log_file: true


# Configuration for the live preview transcriber.
# This instance runs continuously on small chunks of audio for a real-time feed.
preview_transcriber:
    # A smaller, faster model is recommended for the preview.
    model: "Systran/faster-whisper-medium"
    compute_type: "default"
    device: "cuda"
    gpu_device_index: 0
    batch_size: 16
    beam_size: 3 # Smaller beam size for faster preview

    # VAD settings optimized for quick, sentence-by-sentence transcription.
    silero_sensitivity: 0.4
    silero_use_onnx: false
    post_speech_silence_duration: 0.5 # Shorter silence duration for faster chunking
    min_length_of_recording: 1.0

    # Prevent the library from creating its own log file (realtimestt.log).
    no_log_file: true


# Console display settings.
display:
    # If true, the live audio waveform will be displayed during recording.
    # Requires 'cava' to be installed. Disabling this can save CPU resources.
    show_waveform: true


# Global audio settings for the microphone input.
audio:
    # Manually specify the audio input device index. Find indices by running `list_audio_devices.py`.
    # Set to `null` (or leave blank) if `use_default_input` is true.
    input_device_index: 21

    # If true, the application will automatically find the default system microphone.
    # If false, it will use the `input_device_index` specified above.
    use_default_input: false


# Configuration for application logging.
logging:
    # Logging level. Options: "DEBUG", "INFO", "WARNING", "ERROR"
    level: "INFO"

    # Whether to also print log messages to the console. (Useful for debugging)
    console_output: false

    # Base name for the application's main log file.
    file_name: "stt_orchestrator.log"

    # Directory to store log files, relative to the SCRIPT folder.
    # To place logs in the project's root directory, use "..".
    # To place them in the SCRIPT directory, use ".".
    directory: ".."